version: '3.9'

services:
  pg:
    image: postgres:17
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shop"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

  fastapi:
    build: .
    container_name: fastapi_app
    env_file:
      - ./fastapi-application/.env
    ports:
      - "8000:8080"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ./fastapi-application:/FastapiBse/fastapi-application

volumes:
  pgdata: